import { boolean, integer, numeric, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

export const products = pgTable('products', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  code: text('code').notNull(),
  // 'Chinese Pokémon Products' | 'Acrylic Cases'
  category: text('category').notNull(),
  // Gem Series | CSV Series | Blind Box (under Chinese Pokémon Products)
  // ETB Case | Booster Box Case | SPC Box Case (under Acrylic Cases)
  subcategory: text('subcategory').notNull(),
  price: numeric('price', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  compareAtPrice: numeric('compare_at_price', { precision: 10, scale: 2, mode: 'number' }),
  stock: integer('stock').notNull().default(0),
  squareVariationId: text('square_variation_id'),
  img: text('img'),
  // Tablet/mobile are optional — a viewport falls back to `img` (the
  // desktop/default version) when its size-specific version isn't set.
  // These are admin-supplied pre-sized files, not generated by the app.
  imgTablet: text('img_tablet'),
  imgMobile: text('img_mobile'),
  imgAlt: text('img_alt'),
  images: text('images').array().notNull().default([]),
  preorder: boolean('preorder').notNull().default(false),
  // Lets a product be linked to Square and fully set up while still hidden
  // from the public shop, e.g. staging a listing before its street date.
  published: boolean('published').notNull().default(true),
  placeholder: text('placeholder'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash'),
  googleId: text('google_id').unique(),
  name: text('name'),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  // Null until verified. New password signups must verify via emailed code
  // before they can log in; Google signups are stamped verified immediately
  // (Google's own email_verified claim already proves ownership) — see
  // google-auth.ts / customers.ts. No default here deliberately — existing
  // rows are backfilled once in the migration, new rows start unverified.
  emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// One pending code per user — userId as the primary key means a resend just
// overwrites this row instead of accumulating history (unlike authEvents,
// there's no value in keeping old/used codes around).
export const emailVerificationCodes = pgTable('email_verification_codes', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  attempts: integer('attempts').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Same shape/lifecycle as emailVerificationCodes, kept as a separate table
// since the two mean different things — a valid email-verification code
// should never double as a password-reset code or vice versa.
export const passwordResetCodes = pgTable('password_reset_codes', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  attempts: integer('attempts').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Lightweight security/support log — separate from Google Analytics, which
// tracks anonymous browsing behavior. This tracks account-security-relevant
// actions on known accounts: signups, logins (successful and failed),
// Google-account linking. `email` is stored alongside `userId` so a failed
// login against an email with no matching account still leaves a record.
export const authEvents = pgTable('auth_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  email: text('email'),
  type: text('type').notNull(), // signup | login | login_failed | google_link | password_reset
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const orders = pgTable('orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderNo: integer('order_no').notNull().unique(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  // Whether the shopper had an active session at checkout — independent of
  // whether userId ends up set (a guest checkout under an email that
  // already has an account still gets linked, but checkoutMode still
  // records that it happened while logged out).
  checkoutMode: text('checkout_mode').notNull().default('guest'), // guest | account
  email: text('email'),
  phone: text('phone'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  street: text('street'),
  apartment: text('apartment'),
  city: text('city'),
  // Two-letter USPS state code — drives sales tax (currently WA only, see
  // src/server/tax.ts) as well as being part of the shipping address itself.
  state: text('state'),
  zip: text('zip'),
  // Always populated (mirrors the shipping columns above when the shopper
  // checked "use shipping address as billing address" — the common case —
  // rather than left null, so admin display never has to special-case it).
  billingFirstName: text('billing_first_name'),
  billingLastName: text('billing_last_name'),
  billingStreet: text('billing_street'),
  billingApartment: text('billing_apartment'),
  billingCity: text('billing_city'),
  billingState: text('billing_state'),
  billingZip: text('billing_zip'),
  shipMethod: text('ship_method').notNull(),
  subtotal: numeric('subtotal', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  shippingCost: numeric('shipping_cost', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  tax: numeric('tax', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  total: numeric('total', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  paymentStatus: text('payment_status').notNull().default('unpaid'), // unpaid | paid | test | failed
  squarePaymentId: text('square_payment_id'),
  // Human-readable summary of how the order was paid, e.g. "Visa •••• 4242"
  // or "Apple Pay" — derived from Square's already-redacted payment
  // response (never a full card number), shown on receipts as reference.
  paymentMethodSummary: text('payment_method_summary'),
  // Square's own fraud assessment: NORMAL | MODERATE | HIGH. Only present
  // for accounts Square has enrolled in risk evaluation — null elsewhere
  // (including every test-mode order, and wallet payments like Apple Pay
  // which don't carry AVS/CVV). Never used to auto-block a charge — this is
  // a review signal for the admin orders list, nothing more.
  riskLevel: text('risk_level'),
  // AVS_MATCH | AVS_NOT_CHECKED | AVS_REJECTED | ... — whether the billing
  // address given at checkout matched what the card issuer has on file.
  avsStatus: text('avs_status'),
  // CVV_ACCEPTED | CVV_NOT_CHECKED | CVV_REJECTED | ... same idea, for the
  // card's security code.
  cvvStatus: text('cvv_status'),
  // pending | partially_shipped | shipped | cancelled. The first three are
  // derived from shipments (see computeFulfillmentStatus in lib/shipments.ts)
  // whenever a shipment is recorded — only "cancelled" and reverting to
  // "pending" are ever set directly by an admin action.
  fulfillmentStatus: text('fulfillment_status').notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Timestamped fulfillment-status timeline per order (pending -> shipped ->
// cancelled etc.) — the order row only holds the *current* status, this is
// the history of how it got there.
export const orderStatusEvents = pgTable('order_status_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  status: text('status').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Declined/failed Square charges. No order row exists for these (the order
// insert only happens after a successful charge), so this is the only
// record a failed attempt leaves behind.
export const paymentAttempts = pgTable('payment_attempts', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  email: text('email'),
  amount: numeric('amount', { precision: 10, scale: 2, mode: 'number' }),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Admin-made edits to a product's price/compare-at-price/stock — separate
// from the per-order stock decrements that happen automatically on sale.
export const productEditEvents = pgTable('product_edit_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  productId: text('product_id').references(() => products.id, { onDelete: 'set null' }),
  productName: text('product_name').notNull(),
  field: text('field').notNull(), // price | compareAtPrice | stock
  oldValue: text('old_value'),
  newValue: text('new_value'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Refunds reported by Square via webhook. Kept separate from
// orders.paymentStatus (paid/test/failed/unpaid) rather than overloading
// it, since a refund can be partial and the original charge outcome is
// still worth keeping distinct from the refund outcome.
export const refundEvents = pgTable('refund_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
  squarePaymentId: text('square_payment_id'),
  squareRefundId: text('square_refund_id').unique(),
  amount: numeric('amount', { precision: 10, scale: 2, mode: 'number' }),
  status: text('status'), // Square refund status: PENDING | COMPLETED | REJECTED | FAILED
  reason: text('reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Every customer-facing email attempt tied to an order — order confirmation
// and shipment notices so far. Lets admin see whether a given send actually
// went out instead of that only living in Cloudflare's worker logs.
export const emailEvents = pgTable('email_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
  email: text('email'),
  type: text('type').notNull(), // order_confirmation | shipment_notice
  status: text('status').notNull(), // sent | failed | skipped (no email on file / sending not configured)
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const orderItems = pgTable('order_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  productId: text('product_id').notNull(),
  productName: text('product_name').notNull(),
  productCode: text('product_code').notNull(),
  // Snapshot of the product's primary photo at order time — like
  // productName/productCode/unitPrice, kept stable even if the product's
  // image later changes or the product itself is deleted.
  img: text('img'),
  unitPrice: numeric('unit_price', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  qty: integer('qty').notNull(),
})

// An order can ship in more than one package (e.g. part USPS, part UPS
// because of a backorder or box-size split) — each package is its own
// shipment row here, rather than the order holding a single carrier/
// tracking number. Most orders still ship in exactly one shipment covering
// every item, which is the default the admin UI pre-fills.
export const shipments = pgTable('shipments', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  carrier: text('carrier'),
  trackingNumber: text('tracking_number'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// How much of a given order_item went into a given shipment — a single
// line (e.g. "3x Booster Box") can itself be split across shipments, so
// this is a quantity, not a boolean "included" flag.
export const shipmentItems = pgTable('shipment_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  shipmentId: uuid('shipment_id')
    .notNull()
    .references(() => shipments.id, { onDelete: 'cascade' }),
  orderItemId: uuid('order_item_id')
    .notNull()
    .references(() => orderItems.id, { onDelete: 'cascade' }),
  qty: integer('qty').notNull(),
})

export const orderCounters = pgTable('order_counters', {
  id: text('id').primaryKey(),
  nextOrderNo: integer('next_order_no').notNull(),
})

// General marketing list (new drops, restocks) — separate from customer
// accounts (users) since a subscriber never needs to log in. Fed by the
// homepage signup form, the checkout opt-in checkbox, and admin actions.
// Holds only *current* state (email unique) — unsubscribedAt null means
// currently subscribed, set means they left. subscribedAt is the most
// recent (re)subscribe time; createdAt is when this email first ever
// subscribed. Full subscribe/unsubscribe/resubscribe history lives in
// subscriberEvents below, same split as orders/orderStatusEvents.
export const subscribers = pgTable('subscribers', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  source: text('source').notNull(), // source of the most recent (re)subscribe: 'homepage' | 'checkout' | 'admin'
  subscribedAt: timestamp('subscribed_at', { withTimezone: true }).notNull().defaultNow(),
  unsubscribedAt: timestamp('unsubscribed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Append-only log of every subscribe/unsubscribe transition — this is what
// answers "did this email leave and come back, and when," not just the
// current state in subscribers above.
export const subscriberEvents = pgTable('subscriber_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull(),
  type: text('type').notNull(), // 'subscribed' | 'unsubscribed'
  source: text('source'), // set for 'subscribed' events only ('homepage' | 'checkout' | 'admin')
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})
