import { boolean, integer, numeric, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

export const products = pgTable('products', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  // 'Chinese Pokémon Products' | 'Acrylic Cases'
  category: text('category').notNull(),
  // Gem Series | CSV Series | Blind Box (under Chinese Pokémon Products)
  // ETB Case | Booster Box Case | SPC Box Case (under Acrylic Cases)
  subcategory: text('subcategory').notNull(),
  price: numeric('price', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  compareAtPrice: numeric('compare_at_price', { precision: 10, scale: 2, mode: 'number' }),
  stock: integer('stock').notNull().default(0),
  squareVariationId: text('square_variation_id'),
  // GS1 GTIN-13 (UPC/EAN barcode) — same field name/format Square uses on
  // its own catalog items, kept here rather than read live from Square
  // since it's static (never changes with stock/price) and not every
  // product is necessarily linked to Square. Feeds a future Google
  // Merchant Center product feed; validated (13 digits + correct check
  // digit) in admin.ts, not at the DB level, since it's optional per
  // product (many won't have one yet).
  gtin: text('gtin'),
  // The manufacturer/IP brand shown to shoppers (e.g. "Pokémon") — not the
  // seller name, which Merchant Center already knows separately. Near-
  // constant across this catalog today, but a real column rather than a
  // hardcoded value in case a different licensed line is ever carried.
  brand: text('brand'),
  // Google's condition [condition] values: new | used | refurbished — this
  // catalog needs it because the same GTIN/product can legitimately be
  // sold both still-sealed ("new") and opened-by-us-to-reveal-contents
  // ("used"); Google's own definition of "new" requires unopened original
  // packaging, so an opened item must say "used" or the listing risks a
  // condition-mismatch flag against its own description.
  condition: text('condition'),
  // Google's google_product_category [google_product_category] — the
  // exact taxonomy string/ID from Merchant Center's own category picker,
  // e.g. "Arts & Entertainment > Hobbies & Creative Arts > Collectibles >
  // Collectible Trading Cards". Deliberately free text filled in by admin
  // per product/subcategory rather than a hardcoded per-subcategory
  // mapping in code — the exact taxonomy path needs to come from Google's
  // own current category list, not guessed.
  googleProductCategory: text('google_product_category'),
  // Per-unit weight in pounds — needed to get a real Shippo rate quote for
  // Alaska/Hawaii orders (see resolveHiAkShippingRate in server/shippo.ts).
  // Nullable/admin-filled like gtin/brand/etc; a product with no weight set
  // falls back to a conservative default in that lookup rather than
  // quoting nothing.
  weightLb: numeric('weight_lb', { precision: 6, scale: 3, mode: 'number' }),
  img: text('img'),
  // Tablet/mobile are optional — a viewport falls back to `img` (the
  // desktop/default version) when its size-specific version isn't set.
  // These are admin-supplied pre-sized files, not generated by the app.
  imgTablet: text('img_tablet'),
  imgMobile: text('img_mobile'),
  imgAlt: text('img_alt'),
  images: text('images').array().notNull().default([]),
  // Free-form collection labels (e.g. "Gem Series", "CSV Series") — see
  // ProductSubcategory in lib/products.ts for why these are tags rather
  // than a fixed subcategory.
  tags: text('tags').array().notNull().default([]),
  // Rank within the homepage "Best Selling" / "New & Upcoming" sections and
  // their "View All" pages — lower shows first. Every product participates
  // (unlike tags, there's no separate opt-in): null means unranked, and
  // unranked products fill in after the ranked ones, newest first. Two
  // separate columns (not one shared order, and not reusing tags) because a
  // product's position in one has nothing to do with the other.
  bestSellingRank: integer('best_selling_rank'),
  newAndUpcomingRank: integer('new_and_upcoming_rank'),
  // Absolute opt-out of the "unranked products fill in after the curated
  // ones" behavior above — e.g. a preorder that isn't shippable yet
  // shouldn't show up as Best Selling filler just because it's newest.
  // Independent of comingSoon/preorder (admin decides per product, not an
  // automatic rule) and wins over everything else: a hidden product never
  // shows in that section, curated or not.
  hideFromBestSelling: boolean('hide_from_best_selling').notNull().default(false),
  hideFromNewAndUpcoming: boolean('hide_from_new_and_upcoming').notNull().default(false),
  // Per-product description shown on its detail page. Falls back to a
  // generic trust-building paragraph on the frontend when empty — not
  // every product needs custom copy written before it can go live.
  description: text('description'),
  preorder: boolean('preorder').notNull().default(false),
  // In stock and purchasable now, unlike preorder — but physical fulfillment
  // is temporarily delayed (e.g. stock is in transit to us), so an order
  // containing it ships as one shipment once it arrives rather than
  // splitting. Doesn't block mixing with other items the way preorder does
  // (see hasMixedPreorderCart) — it's a warning, not a hard rule, and is
  // meant to be a short-lived admin toggle, not a permanent product trait.
  shipsWithDelay: boolean('ships_with_delay').notNull().default(false),
  // Listed and visible in the shop, but not yet purchasable — no price
  // shown, cart/checkout refuses it server-side too (see placeOrder), not
  // just a disabled button client-side. Distinct from `preorder` (which IS
  // purchasable now, for future shipment) and from `published` (which hides
  // it from the shop entirely).
  comingSoon: boolean('coming_soon').notNull().default(false),
  // Lets a product be linked to Square and fully set up while still hidden
  // from the public shop, e.g. staging a listing before its street date.
  published: boolean('published').notNull().default(true),
  placeholder: text('placeholder'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash'),
  googleId: text('google_id').unique(),
  name: text('name'),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  // Null until verified. New password signups must verify via emailed code
  // before they can log in; Google signups are stamped verified immediately
  // (Google's own email_verified claim already proves ownership) — see
  // google-auth.ts / customers.ts. No default here deliberately — existing
  // rows are backfilled once in the migration, new rows start unverified.
  emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// One pending code per user — userId as the primary key means a resend just
// overwrites this row instead of accumulating history (unlike authEvents,
// there's no value in keeping old/used codes around).
export const emailVerificationCodes = pgTable('email_verification_codes', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  attempts: integer('attempts').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Same shape/lifecycle as emailVerificationCodes, kept as a separate table
// since the two mean different things — a valid email-verification code
// should never double as a password-reset code or vice versa.
export const passwordResetCodes = pgTable('password_reset_codes', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  attempts: integer('attempts').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Lightweight security/support log — separate from Google Analytics, which
// tracks anonymous browsing behavior. This tracks account-security-relevant
// actions on known accounts: signups, logins (successful and failed),
// Google-account linking, and admin panel logins. `email` is stored
// alongside `userId` so a failed login against an email with no matching
// account still leaves a record (admin logins have neither — there's no
// per-admin account, just one shared password).
//
// ipAddress/asn/asOrganization/country come straight from Cloudflare's edge
// (CF-Connecting-IP header and the `cf` object on the incoming Request) —
// free on every plan, no third-party lookup, no ongoing cost. Deliberately
// stores the raw network-owner name rather than a precomputed "is this a
// proxy" verdict: that judgment call belongs at read time (see admin's
// datacenter-keyword check), so it can change as fraud patterns are learned
// without ever needing to re-collect or migrate old rows.
export const authEvents = pgTable('auth_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  email: text('email'),
  type: text('type').notNull(), // signup | login | login_failed | google_link | password_reset | email_verified | admin_login | admin_login_failed
  ipAddress: text('ip_address'),
  asn: integer('asn'),
  asOrganization: text('as_organization'),
  country: text('country'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const orders = pgTable('orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderNo: integer('order_no').notNull().unique(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  // Whether the shopper had an active session at checkout — independent of
  // whether userId ends up set (a guest checkout under an email that
  // already has an account still gets linked, but checkoutMode still
  // records that it happened while logged out).
  checkoutMode: text('checkout_mode').notNull().default('guest'), // guest | account
  email: text('email'),
  phone: text('phone'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  street: text('street'),
  apartment: text('apartment'),
  city: text('city'),
  // Two-letter USPS state code — drives sales tax (currently WA only, see
  // src/server/tax.ts) as well as being part of the shipping address itself.
  state: text('state'),
  zip: text('zip'),
  // Always populated (mirrors the shipping columns above when the shopper
  // checked "use shipping address as billing address" — the common case —
  // rather than left null, so admin display never has to special-case it).
  billingFirstName: text('billing_first_name'),
  billingLastName: text('billing_last_name'),
  billingStreet: text('billing_street'),
  billingApartment: text('billing_apartment'),
  billingCity: text('billing_city'),
  billingState: text('billing_state'),
  billingZip: text('billing_zip'),
  shipMethod: text('ship_method').notNull(),
  subtotal: numeric('subtotal', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  shippingCost: numeric('shipping_cost', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  tax: numeric('tax', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  // Gross order value — what the customer got in goods/shipping/tax. Doesn't
  // subtract creditApplied below; that's what was ACTUALLY charged to a
  // card, kept separate so a $0-card order (fully covered by credit) still
  // shows its true value here, not $0.
  total: numeric('total', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  // Store credit redeemed against this order, if any — see
  // server/store-credit.ts. 0 for the vast majority of orders.
  creditApplied: numeric('credit_applied', { precision: 10, scale: 2, mode: 'number' }).notNull().default(0),
  paymentStatus: text('payment_status').notNull().default('unpaid'), // unpaid | paid | test | failed
  squarePaymentId: text('square_payment_id'),
  // Human-readable summary of how the order was paid, e.g. "Visa •••• 4242"
  // or "Apple Pay" — derived from Square's already-redacted payment
  // response (never a full card number), shown on receipts as reference.
  paymentMethodSummary: text('payment_method_summary'),
  // Square's own fraud assessment: NORMAL | MODERATE | HIGH. Only present
  // for accounts Square has enrolled in risk evaluation — null elsewhere
  // (including every test-mode order, and wallet payments like Apple Pay
  // which don't carry AVS/CVV). Never used to auto-block a charge — this is
  // a review signal for the admin orders list, nothing more.
  riskLevel: text('risk_level'),
  // AVS_MATCH | AVS_NOT_CHECKED | AVS_REJECTED | ... — whether the billing
  // address given at checkout matched what the card issuer has on file.
  avsStatus: text('avs_status'),
  // CVV_ACCEPTED | CVV_NOT_CHECKED | CVV_REJECTED | ... same idea, for the
  // card's security code.
  cvvStatus: text('cvv_status'),
  // pending | partially_shipped | shipped | cancelled. The first three are
  // derived from shipments (see computeFulfillmentStatus in lib/shipments.ts)
  // whenever a shipment is recorded — only "cancelled" and reverting to
  // "pending" are ever set directly by an admin action.
  fulfillmentStatus: text('fulfillment_status').notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Timestamped fulfillment-status timeline per order (pending -> shipped ->
// cancelled etc.) — the order row only holds the *current* status, this is
// the history of how it got there.
export const orderStatusEvents = pgTable('order_status_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  status: text('status').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Declined/failed Square charges. No order row exists for these (the order
// insert only happens after a successful charge), so this is the only
// record a failed attempt leaves behind.
export const paymentAttempts = pgTable('payment_attempts', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  email: text('email'),
  amount: numeric('amount', { precision: 10, scale: 2, mode: 'number' }),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Admin-made edits to a product's price/compare-at-price/stock — separate
// from the per-order stock decrements that happen automatically on sale.
export const productEditEvents = pgTable('product_edit_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  productId: text('product_id').references(() => products.id, { onDelete: 'set null' }),
  productName: text('product_name').notNull(),
  field: text('field').notNull(), // price | compareAtPrice | stock
  oldValue: text('old_value'),
  newValue: text('new_value'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Refunds reported by Square via webhook. Kept separate from
// orders.paymentStatus (paid/test/failed/unpaid) rather than overloading
// it, since a refund can be partial and the original charge outcome is
// still worth keeping distinct from the refund outcome.
export const refundEvents = pgTable('refund_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
  squarePaymentId: text('square_payment_id'),
  squareRefundId: text('square_refund_id').unique(),
  amount: numeric('amount', { precision: 10, scale: 2, mode: 'number' }),
  status: text('status'), // Square refund status: PENDING | COMPLETED | REJECTED | FAILED
  reason: text('reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Every customer-facing email attempt tied to an order — order confirmation
// and shipment notices so far. Lets admin see whether a given send actually
// went out instead of that only living in Cloudflare's worker logs.
export const emailEvents = pgTable('email_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
  email: text('email'),
  type: text('type').notNull(), // order_confirmation | shipment_notice | store_credit_issued
  status: text('status').notNull(), // sent | failed | skipped (no email on file / sending not configured)
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const orderItems = pgTable('order_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  productId: text('product_id').notNull(),
  productName: text('product_name').notNull(),
  // Snapshot of the product's primary photo at order time — like
  // productName/unitPrice, kept stable even if the product's image later
  // changes or the product itself is deleted.
  img: text('img'),
  unitPrice: numeric('unit_price', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  qty: integer('qty').notNull(),
})

// An order can ship in more than one package (e.g. part USPS, part UPS
// because of a backorder or box-size split) — each package is its own
// shipment row here, rather than the order holding a single carrier/
// tracking number. Most orders still ship in exactly one shipment covering
// every item, which is the default the admin UI pre-fills.
export const shipments = pgTable('shipments', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  carrier: text('carrier'),
  trackingNumber: text('tracking_number'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// How much of a given order_item went into a given shipment — a single
// line (e.g. "3x Booster Box") can itself be split across shipments, so
// this is a quantity, not a boolean "included" flag.
export const shipmentItems = pgTable('shipment_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  shipmentId: uuid('shipment_id')
    .notNull()
    .references(() => shipments.id, { onDelete: 'cascade' }),
  orderItemId: uuid('order_item_id')
    .notNull()
    .references(() => orderItems.id, { onDelete: 'cascade' }),
  qty: integer('qty').notNull(),
})

export const orderCounters = pgTable('order_counters', {
  id: text('id').primaryKey(),
  nextOrderNo: integer('next_order_no').notNull(),
})

// Orders placed through a different storefront (currently DropNotify) that
// sells against this same shared Square inventory/location. Deliberately
// walled off from orders/order_items rather than imported into them —
// these never go through checkout, payment, or fulfillment status here,
// they exist purely so admin can see what shipped, attach a carrier/
// tracking number, and fire the "your order has shipped" email. Square is
// the source of truth for payment and inventory on these; this table is
// just a to-do list plus a record of what we've already sent an email for.
export const marketplaceOrders = pgTable('marketplace_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  // Square's order id — the dedup key so a re-sync never imports the same
  // order twice.
  squareOrderId: text('square_order_id').notNull().unique(),
  // Square's order.source.name (e.g. "DropNotify") — kept per-row rather
  // than assumed, since which names count as "marketplace" is admin-
  // configurable (see MARKETPLACE_ORDER_SOURCES) and can change over time.
  sourceName: text('source_name').notNull(),
  // Square's order.reference_id — a merchant-supplied order number (e.g.
  // DropNotify sets its own "DN-003-BJEY7K"-style reference), shown in the
  // shipped email so it reads as a real order rather than a bare "your
  // order." Null if the other storefront never set one.
  referenceId: text('reference_id'),
  email: text('email'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  phone: text('phone'),
  street: text('street'),
  apartment: text('apartment'),
  city: text('city'),
  state: text('state'),
  zip: text('zip'),
  // When Square recorded the order — preserved from Square rather than
  // defaulted, so these sort correctly alongside when they actually
  // happened, not when we happened to run a sync.
  placedAt: timestamp('placed_at', { withTimezone: true }).notNull(),
  carrier: text('carrier'),
  trackingNumber: text('tracking_number'),
  // Set once admin has entered tracking and the shipment email has been
  // attempted — null means still awaiting action, regardless of what
  // emailStatus/emailError end up being (a failed send still counts as
  // "handled," not "still pending").
  shippedAt: timestamp('shipped_at', { withTimezone: true }),
  emailStatus: text('email_status'), // sent | failed | skipped
  emailError: text('email_error'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const marketplaceOrderItems = pgTable('marketplace_order_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  marketplaceOrderId: uuid('marketplace_order_id')
    .notNull()
    .references(() => marketplaceOrders.id, { onDelete: 'cascade' }),
  productName: text('product_name').notNull(),
  img: text('img'),
  // Kept even after img is resolved so a later sync can re-look-up the
  // photo (Square catalog updated, or the item got linked to one of our
  // own products afterward) without needing to re-fetch the whole order.
  squareCatalogObjectId: text('square_catalog_object_id'),
  unitPrice: numeric('unit_price', { precision: 10, scale: 2, mode: 'number' }),
  qty: integer('qty').notNull(),
})

// Same idea as shipments/shipmentItems above, for marketplace orders — a
// DropNotify (etc.) order can also go out in more than one package.
// marketplaceOrders keeps its own carrier/trackingNumber/shippedAt/
// emailStatus/emailError columns too: those now mirror the *most recent*
// shipment (for quick-glance display and for orders shipped before this
// table existed, which have no rows here) while shippedAt specifically
// still only gets set once nothing is left to ship — see adminCreateMarketplaceShipment.
export const marketplaceShipments = pgTable('marketplace_shipments', {
  id: uuid('id').primaryKey().defaultRandom(),
  marketplaceOrderId: uuid('marketplace_order_id')
    .notNull()
    .references(() => marketplaceOrders.id, { onDelete: 'cascade' }),
  carrier: text('carrier'),
  trackingNumber: text('tracking_number'),
  emailStatus: text('email_status'), // sent | failed | skipped
  emailError: text('email_error'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// How much of a given marketplace_order_item went into a given
// marketplace_shipment — mirrors shipment_items above.
export const marketplaceShipmentItems = pgTable('marketplace_shipment_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  shipmentId: uuid('shipment_id')
    .notNull()
    .references(() => marketplaceShipments.id, { onDelete: 'cascade' }),
  marketplaceOrderItemId: uuid('marketplace_order_item_id')
    .notNull()
    .references(() => marketplaceOrderItems.id, { onDelete: 'cascade' }),
  qty: integer('qty').notNull(),
})

// General marketing list (new drops, restocks) — separate from customer
// accounts (users) since a subscriber never needs to log in. Fed by the
// homepage signup form, the checkout opt-in checkbox, and admin actions.
// Holds only *current* state (email unique) — unsubscribedAt null means
// currently subscribed, set means they left. subscribedAt is the most
// recent (re)subscribe time; createdAt is when this email first ever
// subscribed. Full subscribe/unsubscribe/resubscribe history lives in
// subscriberEvents below, same split as orders/orderStatusEvents.
export const subscribers = pgTable('subscribers', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  // Only ever populated from checkout (the homepage form doesn't ask for
  // one) — lets emails greet someone by name instead of a blank.
  firstName: text('first_name'),
  source: text('source').notNull(), // source of the most recent (re)subscribe: 'homepage' | 'checkout' | 'admin'
  subscribedAt: timestamp('subscribed_at', { withTimezone: true }).notNull().defaultNow(),
  unsubscribedAt: timestamp('unsubscribed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Append-only log of every subscribe/unsubscribe transition — this is what
// answers "did this email leave and come back, and when," not just the
// current state in subscribers above.
export const subscriberEvents = pgTable('subscriber_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull(),
  type: text('type').notNull(), // 'subscribed' | 'unsubscribed'
  source: text('source'), // set for 'subscribed' events only ('homepage' | 'checkout' | 'admin')
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Fast, atomically-updated current balance — same pattern as products.stock
// (guarded UPDATE ... WHERE balance >= amount prevents a double-spend race,
// see server/store-credit.ts's redeemStoreCredit). storeCreditEvents below
// is the append-only audit trail, same relationship as products.stock has
// to productEditEvents. One row per user, created on first issue.
export const storeCreditBalances = pgTable('store_credit_balances', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  balance: numeric('balance', { precision: 10, scale: 2, mode: 'number' }).notNull().default(0),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// Every dollar issued or spent, permanently — balance above is derivable
// from summing these, but kept as a separate fast-path column rather than
// recomputed by aggregate on every read (see the comment there). amount is
// signed: positive for issued/reversed, negative for redeemed/adjusted-down.
export const storeCreditEvents = pgTable('store_credit_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  type: text('type').notNull(), // issued | redeemed | reversed | adjusted
  amount: numeric('amount', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  // Set on 'redeemed' (which order spent it) and 'reversed' (which refund
  // gave it back) — null for an admin-issued grant or a manual correction.
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
  // Standard category from the admin dropdown (see lib/store-credit.ts) —
  // shown to admin in full, reduced to a generic attribution for the
  // customer (see getStoreCreditHistory in server/store-credit.ts).
  reason: text('reason'),
  // Free-text detail for admin's own bookkeeping — e.g. "combined orders
  // #EBI-102 and #EBI-104 into one shipment, refunding the difference as
  // credit." Admin-only, always: never included in the customer-facing
  // history query, unlike reason above (which is filtered per-request).
  note: text('note'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})
