import { boolean, integer, numeric, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

export const products = pgTable('products', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  code: text('code').notNull(),
  type: text('type').notNull(),
  price: numeric('price', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  compareAtPrice: numeric('compare_at_price', { precision: 10, scale: 2, mode: 'number' }),
  stock: integer('stock').notNull().default(0),
  squareVariationId: text('square_variation_id'),
  img: text('img'),
  // Tablet/mobile are optional — a viewport falls back to `img` (the
  // desktop/default version) when its size-specific version isn't set.
  // These are admin-supplied pre-sized files, not generated by the app.
  imgTablet: text('img_tablet'),
  imgMobile: text('img_mobile'),
  imgAlt: text('img_alt'),
  images: text('images').array().notNull().default([]),
  preorder: boolean('preorder').notNull().default(false),
  placeholder: text('placeholder'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash'),
  googleId: text('google_id').unique(),
  name: text('name'),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  // Null until verified. New password signups must verify via emailed code
  // before they can log in; Google signups are stamped verified immediately
  // (Google's own email_verified claim already proves ownership) — see
  // google-auth.ts / customers.ts. No default here deliberately — existing
  // rows are backfilled once in the migration, new rows start unverified.
  emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// One pending code per user — userId as the primary key means a resend just
// overwrites this row instead of accumulating history (unlike authEvents,
// there's no value in keeping old/used codes around).
export const emailVerificationCodes = pgTable('email_verification_codes', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  attempts: integer('attempts').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Lightweight security/support log — separate from Google Analytics, which
// tracks anonymous browsing behavior. This tracks account-security-relevant
// actions on known accounts: signups, logins (successful and failed),
// Google-account linking. `email` is stored alongside `userId` so a failed
// login against an email with no matching account still leaves a record.
export const authEvents = pgTable('auth_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  email: text('email'),
  type: text('type').notNull(), // signup | login | login_failed | google_link | password_reset
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const orders = pgTable('orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderNo: integer('order_no').notNull().unique(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  // Whether the shopper had an active session at checkout — independent of
  // whether userId ends up set (a guest checkout under an email that
  // already has an account still gets linked, but checkoutMode still
  // records that it happened while logged out).
  checkoutMode: text('checkout_mode').notNull().default('guest'), // guest | account
  email: text('email'),
  firstName: text('first_name'),
  lastName: text('last_name'),
  street: text('street'),
  apartment: text('apartment'),
  city: text('city'),
  zip: text('zip'),
  shipMethod: text('ship_method').notNull(),
  subtotal: numeric('subtotal', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  shippingCost: numeric('shipping_cost', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  tax: numeric('tax', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  total: numeric('total', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  paymentStatus: text('payment_status').notNull().default('unpaid'), // unpaid | paid | test | failed
  squarePaymentId: text('square_payment_id'),
  fulfillmentStatus: text('fulfillment_status').notNull().default('pending'), // pending | shipped | cancelled
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Timestamped fulfillment-status timeline per order (pending -> shipped ->
// cancelled etc.) — the order row only holds the *current* status, this is
// the history of how it got there.
export const orderStatusEvents = pgTable('order_status_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  status: text('status').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Declined/failed Square charges. No order row exists for these (the order
// insert only happens after a successful charge), so this is the only
// record a failed attempt leaves behind.
export const paymentAttempts = pgTable('payment_attempts', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  email: text('email'),
  amount: numeric('amount', { precision: 10, scale: 2, mode: 'number' }),
  errorMessage: text('error_message'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Admin-made edits to a product's price/compare-at-price/stock — separate
// from the per-order stock decrements that happen automatically on sale.
export const productEditEvents = pgTable('product_edit_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  productId: text('product_id').references(() => products.id, { onDelete: 'set null' }),
  productName: text('product_name').notNull(),
  field: text('field').notNull(), // price | compareAtPrice | stock
  oldValue: text('old_value'),
  newValue: text('new_value'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// Refunds reported by Square via webhook. Kept separate from
// orders.paymentStatus (paid/test/failed/unpaid) rather than overloading
// it, since a refund can be partial and the original charge outcome is
// still worth keeping distinct from the refund outcome.
export const refundEvents = pgTable('refund_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'set null' }),
  squarePaymentId: text('square_payment_id'),
  squareRefundId: text('square_refund_id').unique(),
  amount: numeric('amount', { precision: 10, scale: 2, mode: 'number' }),
  status: text('status'), // Square refund status: PENDING | COMPLETED | REJECTED | FAILED
  reason: text('reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const orderItems = pgTable('order_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  orderId: uuid('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  productId: text('product_id').notNull(),
  productName: text('product_name').notNull(),
  productCode: text('product_code').notNull(),
  unitPrice: numeric('unit_price', { precision: 10, scale: 2, mode: 'number' }).notNull(),
  qty: integer('qty').notNull(),
})

export const orderCounters = pgTable('order_counters', {
  id: text('id').primaryKey(),
  nextOrderNo: integer('next_order_no').notNull(),
})
