/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestSellingRouteImport } from './routes/best-selling'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as NewAndUpcomingRouteImport } from './routes/new-and-upcoming'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAffiliateRouteImport } from './routes/account/affiliate'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AccountSignupRouteImport } from './routes/account/signup'
import { Route as AccountVerifyRouteImport } from './routes/account/verify'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAffiliatesRouteImport } from './routes/admin/affiliates'
import { Route as AdminBestSellingRouteImport } from './routes/admin/best-selling'
import { Route as AdminBulkVariantsRouteImport } from './routes/admin/bulk-variants'
import { Route as AdminLinksRouteImport } from './routes/admin/links'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMarketplaceOrdersRouteImport } from './routes/admin/marketplace-orders'
import { Route as AdminNewAndUpcomingRouteImport } from './routes/admin/new-and-upcoming'
import { Route as AdminNotifyMeRouteImport } from './routes/admin/notify-me'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as GoSlugRouteImport } from './routes/go.$slug'
import { Route as LinksSlugRouteImport } from './routes/links.$slug'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersIdRouteImport } from './routes/account/orders/$id'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers/$id'
import { Route as AdminOrderCustomerViewIdRouteImport } from './routes/admin/order-customer-view.$id'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminAffiliatesIdDashboardRouteImport } from './routes/admin/affiliates_.$id.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellingRoute = BestSellingRouteImport.update({
  id: '/best-selling',
  path: '/best-selling',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAndUpcomingRoute = NewAndUpcomingRouteImport.update({
  id: '/new-and-upcoming',
  path: '/new-and-upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAffiliateRoute = AccountAffiliateRouteImport.update({
  id: '/account/affiliate',
  path: '/account/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignupRoute = AccountSignupRouteImport.update({
  id: '/account/signup',
  path: '/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyRoute = AccountVerifyRouteImport.update({
  id: '/account/verify',
  path: '/account/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/admin/affiliates',
  path: '/admin/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBestSellingRoute = AdminBestSellingRouteImport.update({
  id: '/admin/best-selling',
  path: '/admin/best-selling',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBulkVariantsRoute = AdminBulkVariantsRouteImport.update({
  id: '/admin/bulk-variants',
  path: '/admin/bulk-variants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketplaceOrdersRoute = AdminMarketplaceOrdersRouteImport.update({
  id: '/admin/marketplace-orders',
  path: '/admin/marketplace-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewAndUpcomingRoute = AdminNewAndUpcomingRouteImport.update({
  id: '/admin/new-and-upcoming',
  path: '/admin/new-and-upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotifyMeRoute = AdminNotifyMeRouteImport.update({
  id: '/admin/notify-me',
  path: '/admin/notify-me',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksSlugRoute = LinksSlugRouteImport.update({
  id: '/links/$slug',
  path: '/links/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/account/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/admin/customers/$id',
  path: '/admin/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderCustomerViewIdRoute =
  AdminOrderCustomerViewIdRouteImport.update({
    id: '/admin/order-customer-view/$id',
    path: '/admin/order-customer-view/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/admin/products/$id',
  path: '/admin/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAffiliatesIdDashboardRoute =
  AdminAffiliatesIdDashboardRouteImport.update({
    id: '/admin/affiliates_/$id/dashboard',
    path: '/admin/affiliates/$id/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-selling': typeof BestSellingRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/new-and-upcoming': typeof NewAndUpcomingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/account/verify': typeof AccountVerifyRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/best-selling': typeof AdminBestSellingRoute
  '/admin/bulk-variants': typeof AdminBulkVariantsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketplace-orders': typeof AdminMarketplaceOrdersRoute
  '/admin/new-and-upcoming': typeof AdminNewAndUpcomingRoute
  '/admin/notify-me': typeof AdminNotifyMeRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/go/$slug': typeof GoSlugRoute
  '/links/$slug': typeof LinksSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/order-customer-view/$id': typeof AdminOrderCustomerViewIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/affiliates/$id/dashboard': typeof AdminAffiliatesIdDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-selling': typeof BestSellingRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/new-and-upcoming': typeof NewAndUpcomingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/account/verify': typeof AccountVerifyRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/best-selling': typeof AdminBestSellingRoute
  '/admin/bulk-variants': typeof AdminBulkVariantsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketplace-orders': typeof AdminMarketplaceOrdersRoute
  '/admin/new-and-upcoming': typeof AdminNewAndUpcomingRoute
  '/admin/notify-me': typeof AdminNotifyMeRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/go/$slug': typeof GoSlugRoute
  '/links/$slug': typeof LinksSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/order-customer-view/$id': typeof AdminOrderCustomerViewIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/affiliates/$id/dashboard': typeof AdminAffiliatesIdDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-selling': typeof BestSellingRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/new-and-upcoming': typeof NewAndUpcomingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/account/affiliate': typeof AccountAffiliateRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/account/signup': typeof AccountSignupRoute
  '/account/verify': typeof AccountVerifyRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/best-selling': typeof AdminBestSellingRoute
  '/admin/bulk-variants': typeof AdminBulkVariantsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketplace-orders': typeof AdminMarketplaceOrdersRoute
  '/admin/new-and-upcoming': typeof AdminNewAndUpcomingRoute
  '/admin/notify-me': typeof AdminNotifyMeRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/go/$slug': typeof GoSlugRoute
  '/links/$slug': typeof LinksSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/order-customer-view/$id': typeof AdminOrderCustomerViewIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/affiliates_/$id/dashboard': typeof AdminAffiliatesIdDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-selling'
    | '/cart'
    | '/checkout'
    | '/new-and-upcoming'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/sso-callback'
    | '/terms-of-service'
    | '/account/affiliate'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/reset-password'
    | '/account/signup'
    | '/account/verify'
    | '/admin/affiliates'
    | '/admin/best-selling'
    | '/admin/bulk-variants'
    | '/admin/links'
    | '/admin/login'
    | '/admin/marketplace-orders'
    | '/admin/new-and-upcoming'
    | '/admin/notify-me'
    | '/admin/security'
    | '/admin/subscribers'
    | '/go/$slug'
    | '/links/$slug'
    | '/products/$id'
    | '/account/'
    | '/admin/'
    | '/account/orders/$id'
    | '/admin/customers/$id'
    | '/admin/order-customer-view/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/affiliates/$id/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-selling'
    | '/cart'
    | '/checkout'
    | '/new-and-upcoming'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/sso-callback'
    | '/terms-of-service'
    | '/account/affiliate'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/reset-password'
    | '/account/signup'
    | '/account/verify'
    | '/admin/affiliates'
    | '/admin/best-selling'
    | '/admin/bulk-variants'
    | '/admin/links'
    | '/admin/login'
    | '/admin/marketplace-orders'
    | '/admin/new-and-upcoming'
    | '/admin/notify-me'
    | '/admin/security'
    | '/admin/subscribers'
    | '/go/$slug'
    | '/links/$slug'
    | '/products/$id'
    | '/account'
    | '/admin'
    | '/account/orders/$id'
    | '/admin/customers/$id'
    | '/admin/order-customer-view/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/affiliates/$id/dashboard'
  id:
    | '__root__'
    | '/'
    | '/best-selling'
    | '/cart'
    | '/checkout'
    | '/new-and-upcoming'
    | '/privacy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/sso-callback'
    | '/terms-of-service'
    | '/account/affiliate'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/profile'
    | '/account/reset-password'
    | '/account/signup'
    | '/account/verify'
    | '/admin/affiliates'
    | '/admin/best-selling'
    | '/admin/bulk-variants'
    | '/admin/links'
    | '/admin/login'
    | '/admin/marketplace-orders'
    | '/admin/new-and-upcoming'
    | '/admin/notify-me'
    | '/admin/security'
    | '/admin/subscribers'
    | '/go/$slug'
    | '/links/$slug'
    | '/products/$id'
    | '/account/'
    | '/admin/'
    | '/account/orders/$id'
    | '/admin/customers/$id'
    | '/admin/order-customer-view/$id'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/account/orders/'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/affiliates_/$id/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestSellingRoute: typeof BestSellingRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  NewAndUpcomingRoute: typeof NewAndUpcomingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AccountAffiliateRoute: typeof AccountAffiliateRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountSignupRoute: typeof AccountSignupRoute
  AccountVerifyRoute: typeof AccountVerifyRoute
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminBestSellingRoute: typeof AdminBestSellingRoute
  AdminBulkVariantsRoute: typeof AdminBulkVariantsRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketplaceOrdersRoute: typeof AdminMarketplaceOrdersRoute
  AdminNewAndUpcomingRoute: typeof AdminNewAndUpcomingRoute
  AdminNotifyMeRoute: typeof AdminNotifyMeRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  GoSlugRoute: typeof GoSlugRoute
  LinksSlugRoute: typeof LinksSlugRoute
  ProductsIdRoute: typeof ProductsIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminOrderCustomerViewIdRoute: typeof AdminOrderCustomerViewIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminAffiliatesIdDashboardRoute: typeof AdminAffiliatesIdDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-selling': {
      id: '/best-selling'
      path: '/best-selling'
      fullPath: '/best-selling'
      preLoaderRoute: typeof BestSellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-and-upcoming': {
      id: '/new-and-upcoming'
      path: '/new-and-upcoming'
      fullPath: '/new-and-upcoming'
      preLoaderRoute: typeof NewAndUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/affiliate': {
      id: '/account/affiliate'
      path: '/account/affiliate'
      fullPath: '/account/affiliate'
      preLoaderRoute: typeof AccountAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/signup': {
      id: '/account/signup'
      path: '/account/signup'
      fullPath: '/account/signup'
      preLoaderRoute: typeof AccountSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify': {
      id: '/account/verify'
      path: '/account/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/best-selling': {
      id: '/admin/best-selling'
      path: '/admin/best-selling'
      fullPath: '/admin/best-selling'
      preLoaderRoute: typeof AdminBestSellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bulk-variants': {
      id: '/admin/bulk-variants'
      path: '/admin/bulk-variants'
      fullPath: '/admin/bulk-variants'
      preLoaderRoute: typeof AdminBulkVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketplace-orders': {
      id: '/admin/marketplace-orders'
      path: '/admin/marketplace-orders'
      fullPath: '/admin/marketplace-orders'
      preLoaderRoute: typeof AdminMarketplaceOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-and-upcoming': {
      id: '/admin/new-and-upcoming'
      path: '/admin/new-and-upcoming'
      fullPath: '/admin/new-and-upcoming'
      preLoaderRoute: typeof AdminNewAndUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notify-me': {
      id: '/admin/notify-me'
      path: '/admin/notify-me'
      fullPath: '/admin/notify-me'
      preLoaderRoute: typeof AdminNotifyMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/$slug': {
      id: '/links/$slug'
      path: '/links/$slug'
      fullPath: '/links/$slug'
      preLoaderRoute: typeof LinksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/admin/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/order-customer-view/$id': {
      id: '/admin/order-customer-view/$id'
      path: '/admin/order-customer-view/$id'
      fullPath: '/admin/order-customer-view/$id'
      preLoaderRoute: typeof AdminOrderCustomerViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/affiliates_/$id/dashboard': {
      id: '/admin/affiliates_/$id/dashboard'
      path: '/admin/affiliates/$id/dashboard'
      fullPath: '/admin/affiliates/$id/dashboard'
      preLoaderRoute: typeof AdminAffiliatesIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestSellingRoute: BestSellingRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  NewAndUpcomingRoute: NewAndUpcomingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AccountAffiliateRoute: AccountAffiliateRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountSignupRoute: AccountSignupRoute,
  AccountVerifyRoute: AccountVerifyRoute,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminBestSellingRoute: AdminBestSellingRoute,
  AdminBulkVariantsRoute: AdminBulkVariantsRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketplaceOrdersRoute: AdminMarketplaceOrdersRoute,
  AdminNewAndUpcomingRoute: AdminNewAndUpcomingRoute,
  AdminNotifyMeRoute: AdminNotifyMeRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  GoSlugRoute: GoSlugRoute,
  LinksSlugRoute: LinksSlugRoute,
  ProductsIdRoute: ProductsIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminOrderCustomerViewIdRoute: AdminOrderCustomerViewIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminAffiliatesIdDashboardRoute: AdminAffiliatesIdDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
